CS2103JAN2018-F09-B3/main

docs/DeveloperGuide.adoc
docs/UserGuide.adoc

Change links to source files to point to current rather than upstream repo.

Update documentation to match fork

---

docs/DeveloperGuide.adoc

[#6] Add more NFRs

---

docs/UserGuide.adoc
src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/ClearCommand.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/ExitCommand.java
src/main/java/seedu/address/logic/commands/FindCommand.java
src/main/java/seedu/address/logic/commands/HelpCommand.java
src/main/java/seedu/address/logic/commands/HistoryCommand.java
src/main/java/seedu/address/logic/commands/ListCommand.java
src/main/java/seedu/address/logic/commands/RedoCommand.java
src/main/java/seedu/address/logic/commands/SelectCommand.java
src/main/java/seedu/address/logic/commands/UndoCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
src/test/java/seedu/address/testutil/PersonUtil.java

#9 
```
This reduces the amount of typing needed by the user to call the commands.
```

[#9] Add support for command aliases

---

docs/DeveloperGuide.adoc

[#4] DeveloperGuide.adoc: Add User Stories

---

src/main/java/seedu/address/storage/AddressBookStorage.java
src/main/java/seedu/address/storage/StorageManager.java
src/main/java/seedu/address/storage/XmlAddressBookStorage.java

#12 
* Add empty backupAddressBook method to AddressBookStorage interface
* Implement backupAddressBook method in XmlAddressBookStorage class
* Implement backupAddressBook method for StorageManager by calling AddressBookStorage's backup method

[#12] Add backup API for address book storage

---

docs/DeveloperGuide.adoc

[#7] Add terms in glossary for developer guide

---

src/main/java/seedu/address/commons/events/ui/NewResultAvailableEvent.java
src/main/java/seedu/address/ui/CommandBox.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/PersonCard.java
src/main/java/seedu/address/ui/ResultDisplay.java
src/main/java/seedu/address/ui/StatusBarFooter.java
src/main/resources/view/DarkTheme.css
src/main/resources/view/StatusBarFooter.fxml
src/test/java/guitests/guihandles/ResultDisplayHandle.java
src/test/java/guitests/guihandles/StatusBarFooterHandle.java
src/test/java/seedu/address/ui/ResultDisplayTest.java
src/test/java/seedu/address/ui/StatusBarFooterTest.java
src/test/java/systemtests/AddCommandSystemTest.java
src/test/java/systemtests/AddressBookSystemTest.java
src/test/java/systemtests/ClearCommandSystemTest.java
src/test/java/systemtests/DeleteCommandSystemTest.java
src/test/java/systemtests/EditCommandSystemTest.java
src/test/java/systemtests/FindCommandSystemTest.java
src/test/java/systemtests/HelpCommandSystemTest.java
src/test/java/systemtests/SelectCommandSystemTest.java

#11 
- Use different colors for different tags inside person cards.
- Result display shows a different style on error.
- (WIP) Status bar now shows the total number of items.

[#11] Various UI enhancements

---

README.adoc

#23 Changed the old address book README to the one for our CoinBook

[#23] README.adoc: Add product description

---

src/main/java/seedu/address/commons/util/FetchUtil.java
src/main/java/seedu/address/commons/util/JsonUtil.java

[#25] Add fetch utility class to obtain data from external APIs

---

src/main/java/seedu/address/commons/util/JsonUtil.java
src/main/java/seedu/address/ui/ChartsPanel.java
src/test/java/seedu/address/ui/StatusBarFooterTest.java

Push any warnings found after feature PR merge to here instead

v1.1: Fix warnings

---

docs/DeveloperGuide.adoc

#64 
Added Organisation features to dev guide for documentation purposes

#64 Add organisation features to dev guide

---

docs/UserGuide.adoc

[#40] UserGuide.adoc: Indicate on user guide when is each feature coming later

---

docs/UserGuide.adoc

[#40] Update User Guide with Autocomplete feature

---

README.adoc
build.gradle
src/main/java/seedu/address/commons/util/UrlBuilderUtil.java

[#58][#63] Generic URL builder for API calls

---

src/main/java/seedu/address/logic/commands/NotifyCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/model/ReadOnlyRuleBook.java
src/main/java/seedu/address/model/RuleBook.java
src/main/java/seedu/address/model/rule/DuplicateRuleException.java
src/main/java/seedu/address/model/rule/Rule.java
src/main/java/seedu/address/model/rule/UniqueRuleList.java

#61 
Add needed classes in a basic state.

[#61] Prepare for new feature

---

src/main/java/seedu/address/commons/util/StringUtil.java
src/main/java/seedu/address/logic/commands/BuyCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/BuyCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/CoinBook.java
src/main/java/seedu/address/model/coin/Amount.java
src/main/java/seedu/address/model/coin/Coin.java

For: #104 
Has limited functionality as of now. The updated data is also not being
written to disk yet, so is not persistent.
* StringUtil: Add validation for decimals.
* ParserUtil: Add double parsing function.
* BuyCommand, BuyCommandParser: Add new files.
* AddressBookParser: Register new command.
* Amount, Coin: Add various copy constructors.

[#104] BuyCommand: Add new command

---

docs/DeveloperGuide.adoc

Documentation: Formatting & Layout

---

src/main/java/seedu/address/commons/util/StringUtil.java
src/main/java/seedu/address/logic/commands/TagCommand.java
src/main/java/seedu/address/model/CoinBook.java
src/main/java/seedu/address/model/coin/Coin.java
src/main/java/seedu/address/model/coin/Price.java
src/test/java/seedu/address/commons/util/StringUtilTest.java
src/test/java/seedu/address/logic/parser/CoinBookParserTest.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/model/coin/CoinTest.java

Add `buy` command related tests

---

src/main/java/seedu/address/logic/conditionalparser/SyntaxParser.java
src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
src/main/java/seedu/address/logic/parser/FindCommandParser.java
src/main/java/seedu/address/logic/parser/TokenStack.java
src/main/java/seedu/address/model/tag/Tag.java
src/test/java/seedu/address/logic/conditionalparser/SyntaxParserTest.java
src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
src/test/java/seedu/address/logic/parser/TokenStackTest.java
src/test/java/seedu/address/testutil/TestUtil.java

[#117] Add multi-word tags

---

src/main/java/seedu/address/commons/core/Messages.java
src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/BuyCommand.java
src/main/java/seedu/address/logic/commands/CommandTarget.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/SelectCommand.java
src/main/java/seedu/address/logic/commands/SellCommand.java
src/main/java/seedu/address/logic/commands/TagCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
src/main/java/seedu/address/logic/parser/BuyCommandParser.java
src/main/java/seedu/address/logic/parser/CoinBookParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/logic/parser/SellCommandParser.java
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/logic/commands/BuyCommandTest.java
src/test/java/seedu/address/logic/commands/CommandTargetTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
src/test/java/seedu/address/logic/commands/SelectCommandTest.java
src/test/java/seedu/address/logic/commands/TagCommandTest.java
src/test/java/seedu/address/logic/parser/BuyCommandParserTest.java
src/test/java/systemtests/DeleteCommandSystemTest.java
src/test/java/systemtests/SelectCommandSystemTest.java
src/test/java/systemtests/TagCommandSystemTest.java

[#105] Basic commands

---

src/test/java/seedu/address/logic/parser/CoinBookParserTest.java
src/test/java/seedu/address/testutil/CoinUtil.java

Fix broken test

---

collated/functional/ewaldhew.md
collated/test/Eldon-Chung.md
src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/BuyCommand.java
src/main/java/seedu/address/logic/commands/FindCommand.java
src/main/java/seedu/address/logic/commands/SellCommand.java
src/main/java/seedu/address/logic/commands/TagCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
src/main/java/seedu/address/logic/parser/BuyCommandParser.java
src/main/java/seedu/address/logic/parser/FindCommandParser.java
src/main/java/seedu/address/logic/parser/SellCommandParser.java
src/main/java/seedu/address/logic/parser/TagCommandParser.java
src/main/java/seedu/address/logic/parser/TokenType.java
src/main/java/seedu/address/model/coin/Code.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/conditionalparser/SyntaxParserTest.java
src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
src/test/java/seedu/address/logic/parser/BuyCommandParserTest.java
src/test/java/seedu/address/logic/parser/TagCommandParserTest.java
src/test/java/seedu/address/testutil/CoinUtil.java
src/test/java/seedu/address/testutil/TestUtil.java
src/test/java/systemtests/AddCommandSystemTest.java
src/test/java/systemtests/TagCommandSystemTest.java

[#146] TokenType.java: Refactor prefix token type names.

---

src/main/java/seedu/address/model/coin/Amount.java
src/main/java/seedu/address/model/coin/Coin.java

[#146] Coin.java: Refactor get profit, worth and profitability to return Amount

---

src/main/java/seedu/address/model/tag/Tag.java

[#181] Tag: Revise TAG_VALIDATION_REGEX to only allow single worded tag names

---

src/main/java/seedu/address/logic/commands/FindCommand.java
src/main/java/seedu/address/logic/conditions/CodeCondition.java
src/main/java/seedu/address/logic/parser/ConditionGenerator.java
src/main/java/seedu/address/model/coin/Code.java

[#188] Refactor code condition

---

src/main/java/seedu/address/model/coin/Coin.java

[#184] Coin.java: Revise equals method to only check Code attribute

---

src/main/java/seedu/address/logic/commands/CommandTarget.java

[#152] Fix: Add getSourceIndex method in toIndex method in CommandTarget class

---

src/main/java/seedu/address/logic/conditions/AmountCondition.java
src/main/java/seedu/address/logic/conditions/AmountHeldCondition.java
src/main/java/seedu/address/logic/conditions/CurrentPriceCondition.java
src/main/java/seedu/address/logic/conditions/DollarsBoughtCondition.java
src/main/java/seedu/address/logic/conditions/DollarsSoldCondition.java
src/main/java/seedu/address/logic/conditions/MadeCondition.java
src/main/java/seedu/address/logic/conditions/WorthCondition.java
src/main/java/seedu/address/logic/parser/ConditionGenerator.java

[#194] Add amount condition superclass

---

docs/DeveloperGuide.adoc

Edited for brevity, direct tone ("you" phrasing), and simpler language.

DeveloperGuide#Introduction: Proposed changes

---

src/main/java/seedu/address/commons/util/CollectionUtil.java
src/main/java/seedu/address/commons/util/StringUtil.java
src/main/java/seedu/address/logic/commands/BuyCommand.java
src/main/java/seedu/address/logic/commands/SellCommand.java
src/main/java/seedu/address/logic/conditions/CurrentPriceCondition.java
src/main/java/seedu/address/logic/parser/BuyCommandParser.java
src/main/java/seedu/address/logic/parser/ConditionGenerator.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/logic/parser/SellCommandParser.java
src/main/java/seedu/address/model/CoinBook.java
src/main/java/seedu/address/model/coin/Amount.java
src/main/java/seedu/address/model/coin/Coin.java
src/main/java/seedu/address/model/coin/Price.java
src/main/java/seedu/address/storage/XmlAdaptedCoin.java
src/main/java/seedu/address/ui/CoinCard.java
src/test/java/seedu/address/commons/util/StringUtilTest.java
src/test/java/seedu/address/logic/commands/BuyCommandTest.java
src/test/java/seedu/address/logic/parser/BuyCommandParserTest.java
src/test/java/seedu/address/logic/parser/CoinBookParserTest.java
src/test/java/seedu/address/logic/parser/ConditionGeneratorTest.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/model/coin/CoinTest.java
src/test/java/seedu/address/testutil/CoinBuilder.java
src/test/java/seedu/address/ui/testutil/GuiTestAssert.java

For: #109 
Fixes: #143 , #173 , #177

[#109] Coin Amounts fixes

---

src/main/java/seedu/address/commons/core/CoinSubredditList.java
src/main/java/seedu/address/logic/parser/ParserUtil.java

[#196] ParserUtil: Add warning logging for when Find argument parsing fails

---

build.gradle
docs/DeveloperGuide.adoc
docs/UsingGradle.adoc
src/main/java/seedu/address/commons/core/LogsCenter.java
src/main/java/seedu/address/storage/XmlRuleBookStorage.java
src/test/java/systemtests/AddCommandSystemTest.java
src/test/java/systemtests/ClearCommandSystemTest.java
src/test/java/systemtests/DeleteCommandSystemTest.java
src/test/java/systemtests/SystemTestSetupHelper.java

[#203] Rename address to coin in all commands, parameter names, and scripts

---

src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/ViewCommand.java
src/main/java/seedu/address/logic/parser/CoinBookParser.java
src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
src/main/java/seedu/address/logic/parser/ViewCommandParser.java
src/test/java/seedu/address/logic/commands/CommandTargetTest.java
src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
src/test/java/seedu/address/logic/commands/ListCommandTest.java
src/test/java/seedu/address/logic/commands/RedoCommandTest.java
src/test/java/seedu/address/logic/commands/TagCommandTest.java
src/test/java/seedu/address/logic/commands/UndoCommandTest.java
src/test/java/seedu/address/logic/commands/UndoableCommandTest.java
src/test/java/seedu/address/logic/commands/ViewCommandTest.java
src/test/java/seedu/address/logic/parser/CoinBookParserTest.java
src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/logic/parser/TagCommandParserTest.java
src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
src/test/java/seedu/address/testutil/TypicalTargets.java
src/test/java/seedu/address/ui/CoinListPanelTest.java
src/test/java/seedu/address/ui/RuleListPanelTest.java
src/test/java/systemtests/DeleteCommandSystemTest.java
src/test/java/systemtests/HelpCommandSystemTest.java
src/test/java/systemtests/TagCommandSystemTest.java
src/test/java/systemtests/ViewCommandSystemTest.java

* ViewCommand, DeleteCommand: Change to targeted

Fix targeted commands

---

src/main/java/seedu/address/logic/commands/SyncCommand.java
src/main/java/seedu/address/model/CoinBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java

Refactor out json processing in model to command

Refactor sync command

---

src/main/java/seedu/address/logic/commands/SyncCommand.java
src/main/java/seedu/address/model/CoinBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java

Refactor sync command (#207)

---

.gitignore
src/main/java/seedu/address/logic/commands/SellCommand.java
src/test/java/seedu/address/logic/commands/BuyCommandSystemTest.java
src/test/java/seedu/address/logic/commands/FindCommandSystemTest.java
src/test/java/seedu/address/logic/commands/SellCommandSystemTest.java
src/test/java/seedu/address/logic/parser/BuyCommandParserTest.java
src/test/java/seedu/address/logic/parser/SellCommandParserTest.java
src/test/java/seedu/address/testutil/CoinUtil.java
src/test/java/systemtests/AddCommandSystemTest.java
src/test/java/systemtests/CoinBookSystemTest.java
src/test/java/systemtests/DeleteCommandSystemTest.java
src/test/java/systemtests/TagCommandSystemTest.java

#167 
Part 2 includes reinstating previous tests, writing new system tests for Buy and Sell command.

[#162] Refactor tests part 2

---

src/main/java/seedu/address/logic/CommandList.java
src/main/java/seedu/address/logic/Logic.java
src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/ui/CommandBox.java

#54 
* Add basic autocomplete feature for entering command

[#54] Autocomplete feature

---

docs/team/neilish3re.adoc

Update Project Portfolio for neilish3re

Update Project Portfolio for neilish3re

---

src/main/java/seedu/address/model/util/SampleDataUtil.java

[#214] SampleDataUtil: Change Coin names to actual Coin names

---

src/main/java/seedu/address/commons/events/model/CoinChangedEvent.java
src/main/java/seedu/address/logic/RuleChecker.java
src/main/java/seedu/address/logic/conditions/AmountChangeCondition.java
src/main/java/seedu/address/logic/conditions/AmountCondition.java
src/main/java/seedu/address/logic/conditions/AmountHeldChangeCondition.java
src/main/java/seedu/address/logic/conditions/AmountHeldCondition.java
src/main/java/seedu/address/logic/conditions/CurrentPriceChangeCondition.java
src/main/java/seedu/address/logic/conditions/CurrentPriceCondition.java
src/main/java/seedu/address/logic/conditions/DollarsBoughtChangeCondition.java
src/main/java/seedu/address/logic/conditions/DollarsBoughtCondition.java
src/main/java/seedu/address/logic/conditions/DollarsSoldChangeCondition.java
src/main/java/seedu/address/logic/conditions/DollarsSoldCondition.java
src/main/java/seedu/address/logic/conditions/MadeChangeCondition.java
src/main/java/seedu/address/logic/conditions/WorthChangeCondition.java
src/main/java/seedu/address/logic/conditions/WorthCondition.java
src/main/java/seedu/address/logic/parser/ConditionGenerator.java
src/main/java/seedu/address/model/CoinBook.java
src/main/java/seedu/address/model/coin/Coin.java
src/main/java/seedu/address/model/rule/Rule.java

[#59] Add generation of coin change events for rule checker

---

src/main/java/seedu/address/ui/MainWindow.java

MainWindow: Make notifications pop-up

---

src/main/java/seedu/address/logic/commands/SortCommand.java
src/main/java/seedu/address/logic/commands/TagCommand.java
src/main/java/seedu/address/logic/parser/CoinBookParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/logic/parser/SortCommandParser.java
src/main/java/seedu/address/model/CoinBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/coin/UniqueCoinList.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java

#92 
Allows the user to sort coin list in either ascending or descending alphabetical order.

#92 SortCommand feature

---

docs/UserGuide.adoc
src/main/java/seedu/address/commons/events/ui/ShowNotificationRequestEvent.java
src/main/java/seedu/address/logic/RuleChecker.java
src/main/java/seedu/address/logic/commands/ActionCommand.java
src/main/java/seedu/address/logic/commands/NotifyCommand.java
src/main/java/seedu/address/logic/commands/SpawnNotificationCommand.java
src/main/java/seedu/address/model/rule/NotificationRule.java
src/main/java/seedu/address/model/rule/Rule.java
src/main/java/seedu/address/ui/MainWindow.java

[#223] Notifications jump to coin

---

src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/logic/parser/TokenType.java
src/main/java/seedu/address/model/coin/Coin.java
src/main/java/seedu/address/model/coin/Price.java

* TokenType: Add the new prefixes into recognized types
* Coin, Price: Actually implement diffing

NotifyCommand: Fix amount change condition matching

---

src/main/java/seedu/address/MainApp.java
src/main/java/seedu/address/ui/CoinCard.java
src/test/java/seedu/address/TestApp.java

[#225] Sync data on app startup

---

src/main/java/seedu/address/ui/MainWindow.java

[#126] Add loading ui

---

src/main/java/seedu/address/logic/commands/NotifyCommand.java
src/main/java/seedu/address/model/coin/Amount.java
src/main/java/seedu/address/storage/XmlAdaptedRule.java
src/test/data/XmlRuleBookStorageTest/NotXmlFormatRuleBook.xml
src/test/data/XmlRuleBookStorageTest/invalidAndValidRuleRuleBook.xml
src/test/data/XmlRuleBookStorageTest/invalidRuleRuleBook.xml
src/test/java/guitests/guihandles/RuleListPanelHandle.java
src/test/java/seedu/address/logic/RuleCheckerTest.java
src/test/java/seedu/address/logic/commands/ListNotifsCommandTest.java
src/test/java/seedu/address/logic/commands/NotifyCommandTest.java
src/test/java/seedu/address/logic/commands/SpawnNotificationCommandTest.java
src/test/java/seedu/address/logic/parser/ConditionGeneratorTest.java
src/test/java/seedu/address/logic/parser/NotifyCommandParserTest.java
src/test/java/seedu/address/model/ModelManagerTest.java
src/test/java/seedu/address/storage/StorageManagerTest.java
src/test/java/seedu/address/storage/XmlAdaptedRuleTest.java
src/test/java/seedu/address/storage/XmlRuleBookStorageTest.java
src/test/java/seedu/address/storage/XmlSerializableRuleBookTest.java
src/test/java/seedu/address/testutil/NotificationRuleBuilder.java
src/test/java/seedu/address/testutil/TestUtil.java
src/test/java/seedu/address/testutil/TypicalRules.java
src/test/java/seedu/address/ui/RuleListPanelTest.java
src/test/java/systemtests/NotifyCommandSystemTest.java

Notifications: Add tests

---

src/main/java/seedu/address/commons/util/StringUtil.java
src/main/java/seedu/address/model/coin/Amount.java
src/main/java/seedu/address/model/coin/Price.java
src/test/java/seedu/address/commons/util/StringUtilTest.java

Amount: Disallow negative, Better print

---

src/main/java/seedu/address/logic/commands/SyncCommand.java
src/main/java/seedu/address/model/coin/Price.java
src/main/java/seedu/address/ui/ChartsPanel.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/resources/view/ChartsPanel.fxml
src/main/resources/view/DarkTheme.css
src/main/resources/view/Extensions.css
src/main/resources/view/MainWindow.fxml
src/test/java/guitests/guihandles/ChartsPanelHandle.java
src/test/java/seedu/address/ui/ChartsPanelTest.java

[#57] Charts Panel
